/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../ClientApp/app/components/home.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
export class Wrapper_HomeComponent {
  /*private*/ _eventHandler:Function;
  context:import0.HomeComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.HomeComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_HomeComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_HomeComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.HomeComponent>;
  _HomeComponent_0_3:Wrapper_HomeComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HomeComponent_Host0,renderType_HomeComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'home',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_HomeComponent0(this.viewUtils,this,0,this._el_0);
    this._HomeComponent_0_3 = new Wrapper_HomeComponent();
    this.compView_0.create(this._HomeComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._HomeComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HomeComponent) && (0 === requestNodeIndex))) { return this._HomeComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HomeComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const HomeComponentNgFactory:import7.ComponentFactory<import0.HomeComponent> = new import7.ComponentFactory<import0.HomeComponent>('home',View_HomeComponent_Host0,import0.HomeComponent);
const styles_HomeComponent:any[] = ([] as any[]);
var renderType_HomeComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_HomeComponent,{});
export class View_HomeComponent0 extends import1.AppView<import0.HomeComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HomeComponent0,renderType_HomeComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Hello, world!',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'Welcome to your new single-page application, built with:',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,parentRenderNode,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n  ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_8,'a',new import3.InlineArray2(2,'href','https://get.asp.net/'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'ASP.NET Core',(null as any));
    this._text_11 = this.renderer.createText(this._el_8,' and ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_8,'a',new import3.InlineArray2(2,'href','https://msdn.microsoft.com/en-us/library/67ef8sbd.aspx'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'C#',(null as any));
    this._text_14 = this.renderer.createText(this._el_8,' for cross-platform server-side code',(null as any));
    this._text_15 = this.renderer.createText(this._el_6,'\n  ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_6,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_16,'a',new import3.InlineArray2(2,'href','https://angular.io/'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Angular 2',(null as any));
    this._text_19 = this.renderer.createText(this._el_16,' and ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_16,'a',new import3.InlineArray2(2,'href','http://www.typescriptlang.org/'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'TypeScript',(null as any));
    this._text_22 = this.renderer.createText(this._el_16,' for client-side code',(null as any));
    this._text_23 = this.renderer.createText(this._el_6,'\n  ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_6,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_24,'a',new import3.InlineArray2(2,'href','https://webpack.github.io/'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Webpack',(null as any));
    this._text_27 = this.renderer.createText(this._el_24,' for building and bundling client-side resources',(null as any));
    this._text_28 = this.renderer.createText(this._el_6,'\n  ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_6,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_29,'a',new import3.InlineArray2(2,'href','http://getbootstrap.com/'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'Bootstrap',(null as any));
    this._text_32 = this.renderer.createText(this._el_29,' for layout and styling',(null as any));
    this._text_33 = this.renderer.createText(this._el_6,'\n',(null as any));
    this._text_34 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,parentRenderNode,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'To help you get started, we\'ve also set up:',(null as any));
    this._text_37 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,parentRenderNode,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n  ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_38,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_40,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Client-side navigation',(null as any));
    this._text_43 = this.renderer.createText(this._el_40,'. For example, click ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_40,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'Counter',(null as any));
    this._text_46 = this.renderer.createText(this._el_40,' then ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_40,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'Back',(null as any));
    this._text_49 = this.renderer.createText(this._el_40,' to return here.',(null as any));
    this._text_50 = this.renderer.createText(this._el_38,'\n  ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_38,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_51,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Server-side prerendering',(null as any));
    this._text_54 = this.renderer.createText(this._el_51,'. For faster initial loading and improved SEO, your Angular 2 app is prerendered on the server. The resulting HTML is then transferred to the browser where a client-side copy of the app takes over.',(null as any));
    this._text_55 = this.renderer.createText(this._el_38,'\n  ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_38,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_56,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'Webpack dev middleware',(null as any));
    this._text_59 = this.renderer.createText(this._el_56,'. In development mode, there\'s no need to run the ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,this._el_56,'code',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'webpack',(null as any));
    this._text_62 = this.renderer.createText(this._el_56,' build tool. Your client-side resources are dynamically built on demand. Updates are available as soon as you modify any file.',(null as any));
    this._text_63 = this.renderer.createText(this._el_38,'\n  ',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_38,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_64,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'Hot module replacement',(null as any));
    this._text_67 = this.renderer.createText(this._el_64,'. In development mode, you don\'t even need to reload the page after making most changes. Within seconds of saving changes to files, your Angular 2 app will be rebuilt and a new instance injected is into the page.',(null as any));
    this._text_68 = this.renderer.createText(this._el_38,'\n  ',(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,this._el_38,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_69,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'Efficient production builds',(null as any));
    this._text_72 = this.renderer.createText(this._el_69,'. In production mode, development-time features are disabled, and the ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_69,'code',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'webpack',(null as any));
    this._text_75 = this.renderer.createText(this._el_69,' build tool produces minified static CSS and JavaScript files.',(null as any));
    this._text_76 = this.renderer.createText(this._el_38,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._text_76
    ]
    ),(null as any));
    return (null as any);
  }
}