/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../ClientApp/app/portfolio/portfolio-detail/portfolio-detail.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../../../../ClientApp/app/portfolio/shared/portfolio.service';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '@angular/core/src/change_detection/change_detection_util';
import * as import13 from '@angular/core/src/security';
import * as import14 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import18 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import19 from '@angular/common/src/directives/ng_for';
import * as import20 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import21 from '@angular/common/src/location/location_strategy';
import * as import22 from '@angular/router/src/directives/router_link';
export class Wrapper_PortfolioDetailComponent {
  /*private*/ _eventHandler:Function;
  context:import0.PortfolioDetailComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.PortfolioDetailComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_PortfolioDetailComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_PortfolioDetailComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.PortfolioDetailComponent>;
  _PortfolioDetailComponent_0_3:Wrapper_PortfolioDetailComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PortfolioDetailComponent_Host0,renderType_PortfolioDetailComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'portfolio-detail',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_PortfolioDetailComponent0(this.viewUtils,this,0,this._el_0);
    this._PortfolioDetailComponent_0_3 = new Wrapper_PortfolioDetailComponent(this.injectorGet(import8.ActivatedRoute,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex),this.injectorGet(import10.PortfolioService,this.parentIndex));
    this.compView_0.create(this._PortfolioDetailComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._PortfolioDetailComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PortfolioDetailComponent) && (0 === requestNodeIndex))) { return this._PortfolioDetailComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PortfolioDetailComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PortfolioDetailComponentNgFactory:import7.ComponentFactory<import0.PortfolioDetailComponent> = new import7.ComponentFactory<import0.PortfolioDetailComponent>('portfolio-detail',View_PortfolioDetailComponent_Host0,import0.PortfolioDetailComponent);
const styles_PortfolioDetailComponent:any[] = ([] as any[]);
class View_PortfolioDetailComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_PortfolioDetailComponent1,renderType_PortfolioDetailComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-lg-12 text-center'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h1',new import3.InlineArray2(2,'class','page-header'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-spinner fa-spin fa-fw'),(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n      Henter indhold...\n    ',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_PortfolioDetailComponent3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_PortfolioDetailComponent3,renderType_PortfolioDetailComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray4(4,'alt','','class','img-responsive clickCursor'),(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.parentView.parentView.context.getImgSrc(this.parentView.parentView.context.item.imageIndex);
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import13.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.openGallery(this.parentView.parentView.context.item.imageIndex)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_PortfolioDetailComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_PortfolioDetailComponent4,renderType_PortfolioDetailComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'i',new import3.InlineArray2(2,'class','fa-li fa fa-check-square-o'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4:any = import3.inlineInterpolate(1,'',this.context.$implicit,'\n        ');
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_3,currVal_4);
      this._expr_4 = currVal_4;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_PortfolioDetailComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_PortfolioDetailComponent7,renderType_PortfolioDetailComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','col-sm-3 col-xs-6'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray4(4,'alt','','class','img-responsive portfolio-item clickCursor'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4:any = this.parentView.parentView.parentView.parentView.context.getImgSrc(this.parentView.context.index);
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import13.SecurityContext.URL,currVal_4));
      this._expr_4 = currVal_4;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.parentView.parentView.context.openGallery(this.parentView.context.index)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_PortfolioDetailComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import11.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import14.Wrapper_NgIf;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_PortfolioDetailComponent6,renderType_PortfolioDetailComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_2 = new import11.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import15.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import14.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.init(this._text_3,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import16.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = (this.parentView.parentView.parentView.context.item.imageIndex !== this.context.index);
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
    cb(this._text_1,ctx);
    cb(this._vc_2.nativeElement,ctx);
    this._vc_2.visitNestedViewRootNodes(cb,ctx);
    cb(this._text_3,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_PortfolioDetailComponent7(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_PortfolioDetailComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _vc_8:import11.ViewContainer;
  _TemplateRef_8_5:any;
  _NgFor_8_6:import17.Wrapper_NgFor;
  _text_9:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_PortfolioDetailComponent5,renderType_PortfolioDetailComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-lg-12'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h3',new import3.InlineArray2(2,'class','page-header'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Flere billeder',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_8 = new import11.ViewContainer(8,0,this,this._anchor_8);
    this._TemplateRef_8_5 = new import15.TemplateRef_(this,8,this._anchor_8);
    this._NgFor_8_6 = new import17.Wrapper_NgFor(this._vc_8.vcRef,this._TemplateRef_8_5,this.parentView.parentView.injectorGet(import18.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.ref);
    this._text_9 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._anchor_8,
      this._text_9
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import19.NgFor) && (8 === requestNodeIndex))) { return this._NgFor_8_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_8_0_0:any = this.parentView.parentView.context.item.images;
    this._NgFor_8_6.check_ngForOf(currVal_8_0_0,throwOnChange,false);
    this._NgFor_8_6.ngDoCheck(this,this._anchor_8,throwOnChange);
    this._vc_8.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_8.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 8)) { return new View_PortfolioDetailComponent6(this.viewUtils,this,8,this._anchor_8,this._vc_8); }
    return (null as any);
  }
}
class View_PortfolioDetailComponent9 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_PortfolioDetailComponent9,renderType_PortfolioDetailComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import12.UNINITIALIZED;
    this._expr_5 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','columnGallery'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray4(4,'alt','','class','demoGallery img-responsive'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4:any = (this.parentView.parentView.parentView.context.currentIndex === this.context.index);
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'active',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.parentView.parentView.parentView.context.getImgSrc(this.context.index);
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import13.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.parentView.context.setCurrentIndex(this.context.index)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_PortfolioDetailComponent8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _anchor_34:any;
  /*private*/ _vc_34:import11.ViewContainer;
  _TemplateRef_34_5:any;
  _NgFor_34_6:import17.Wrapper_NgFor;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_PortfolioDetailComponent8,renderType_PortfolioDetailComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_42 = import12.UNINITIALIZED;
    this._expr_43 = import12.UNINITIALIZED;
    this._expr_44 = import12.UNINITIALIZED;
    this._expr_45 = import12.UNINITIALIZED;
    this._expr_46 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','portfolioGallery'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','modalGallery'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'span',new import3.InlineArray2(2,'class','closeGallery cursor'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'×',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','modalGallery-content noselect'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','mySlidesGallery'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n          ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'img',new import3.InlineArray2(2,'class','img-responsive'),(null as any));
    this._text_13 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_14 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._text_15 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_7,'h4',new import3.InlineArray2(2,'class','text-center noselect'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n          ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'a',new import3.InlineArray2(2,'class','btn btn-default btn-back'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-2x fa-arrow-left'),(null as any));
    this._text_21 = this.renderer.createText(this._el_18,'\n          ',(null as any));
    this._text_22 = this.renderer.createText(this._el_16,'\n          ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_16,'span',new import3.InlineArray2(2,'class','imgNumber'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'',(null as any));
    this._text_25 = this.renderer.createText(this._el_16,'\n          ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_16,'a',new import3.InlineArray2(2,'class','btn btn-default btn-back'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-2x fa-arrow-right'),(null as any));
    this._text_29 = this.renderer.createText(this._el_26,'\n          ',(null as any));
    this._text_30 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._text_31 = this.renderer.createText(this._el_7,'\n\n        ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n          ',(null as any));
    this._anchor_34 = this.renderer.createTemplateAnchor(this._el_32,(null as any));
    this._vc_34 = new import11.ViewContainer(34,32,this,this._anchor_34);
    this._TemplateRef_34_5 = new import15.TemplateRef_(this,34,this._anchor_34);
    this._NgFor_34_6 = new import17.Wrapper_NgFor(this._vc_34.vcRef,this._TemplateRef_34_5,this.parentView.parentView.injectorGet(import18.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.ref);
    this._text_35 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._text_36 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_37 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_38 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_4));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_18));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_26,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_26));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._anchor_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (34 === requestNodeIndex))) { return this._TemplateRef_34_5; }
    if (((token === import19.NgFor) && (34 === requestNodeIndex))) { return this._NgFor_34_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_34_0_0:any = this.parentView.parentView.context.item.images;
    this._NgFor_34_6.check_ngForOf(currVal_34_0_0,throwOnChange,false);
    this._NgFor_34_6.ngDoCheck(this,this._anchor_34,throwOnChange);
    this._vc_34.detectChangesInNestedViews(throwOnChange);
    const currVal_42:any = (this.parentView.parentView.context.isOpen? 'block': 'none');
    if (import3.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementStyle(this._el_2,'display',((this.viewUtils.sanitizer.sanitize(import13.SecurityContext.STYLE,currVal_42) == null)? (null as any): this.viewUtils.sanitizer.sanitize(import13.SecurityContext.STYLE,currVal_42).toString()));
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = this.parentView.parentView.context.getImgSrc(this.parentView.parentView.context.currentIndex);
    if (import3.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementProperty(this._el_12,'src',this.viewUtils.sanitizer.sanitize(import13.SecurityContext.URL,currVal_43));
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = ((this.parentView.parentView.context.currentIndex != 0)? 'visible': 'hidden');
    if (import3.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementStyle(this._el_18,'visibility',((this.viewUtils.sanitizer.sanitize(import13.SecurityContext.STYLE,currVal_44) == null)? (null as any): this.viewUtils.sanitizer.sanitize(import13.SecurityContext.STYLE,currVal_44).toString()));
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = import3.inlineInterpolate(2,'',(this.parentView.parentView.context.currentIndex + 1),' / ',((this.parentView.parentView.context.item == null)? (null as any): ((this.parentView.parentView.context.item.images == null)? (null as any): this.parentView.parentView.context.item.images.length)),'');
    if (import3.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setText(this._text_24,currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = ((this.parentView.parentView.context.currentIndex != (((this.parentView.parentView.context.item == null)? (null as any): ((this.parentView.parentView.context.item.images == null)? (null as any): this.parentView.parentView.context.item.images.length)) - 1))? 'visible': 'hidden');
    if (import3.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementStyle(this._el_26,'visibility',((this.viewUtils.sanitizer.sanitize(import13.SecurityContext.STYLE,currVal_46) == null)? (null as any): this.viewUtils.sanitizer.sanitize(import13.SecurityContext.STYLE,currVal_46).toString()));
      this._expr_46 = currVal_46;
    }
  }
  destroyInternal():void {
    this._vc_34.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 34)) { return new View_PortfolioDetailComponent9(this.viewUtils,this,34,this._anchor_34,this._vc_34); }
    return (null as any);
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.closeGallery()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.moveSlide(false)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_26(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.moveSlide(true)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_PortfolioDetailComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _RouterLinkWithHref_8_3:import20.Wrapper_RouterLinkWithHref;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _vc_20:import11.ViewContainer;
  _TemplateRef_20_5:any;
  _NgIf_20_6:import14.Wrapper_NgIf;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _vc_35:import11.ViewContainer;
  _TemplateRef_35_5:any;
  _NgFor_35_6:import17.Wrapper_NgFor;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _anchor_40:any;
  /*private*/ _vc_40:import11.ViewContainer;
  _TemplateRef_40_5:any;
  _NgIf_40_6:import14.Wrapper_NgIf;
  _text_41:any;
  _anchor_42:any;
  /*private*/ _vc_42:import11.ViewContainer;
  _TemplateRef_42_5:any;
  _NgIf_42_6:import14.Wrapper_NgIf;
  _text_43:any;
  _arr_57:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_59:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_PortfolioDetailComponent2,renderType_PortfolioDetailComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._arr_57 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_58 = import12.UNINITIALIZED;
    this._expr_59 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-lg-12'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'h1',new import3.InlineArray2(2,'class','page-header'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'a',new import3.InlineArray2(2,'class','btn btn-default btn-back'),(null as any));
    this._RouterLinkWithHref_8_3 = new import20.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import8.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import21.LocationStrategy,this.parentIndex));
    this._text_9 = this.renderer.createText(this._el_8,'\n          ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-2x fa-arrow-left'),(null as any));
    this._text_11 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._text_12 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._vc_20 = new import11.ViewContainer(20,18,this,this._anchor_20);
    this._TemplateRef_20_5 = new import15.TemplateRef_(this,20,this._anchor_20);
    this._NgIf_20_6 = new import14.Wrapper_NgIf(this._vc_20.vcRef,this._TemplateRef_20_5);
    this._text_21 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_16,'\n\n    ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'h3',new import3.InlineArray2(2,'class','projectDescHeader'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Projekt Beskrivelse',(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_23,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_23,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'Projekt Teknologier',(null as any));
    this._text_32 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_23,'ul',new import3.InlineArray2(2,'class','fa-ul'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_33,(null as any));
    this._vc_35 = new import11.ViewContainer(35,33,this,this._anchor_35);
    this._TemplateRef_35_5 = new import15.TemplateRef_(this,35,this._anchor_35);
    this._NgFor_35_6 = new import17.Wrapper_NgFor(this._vc_35.vcRef,this._TemplateRef_35_5,this.parentView.injectorGet(import18.IterableDiffers,this.parentIndex),this.parentView.ref);
    this._text_36 = this.renderer.createText(this._el_33,'\n      ',(null as any));
    this._text_37 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._text_38 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._text_39 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._anchor_40 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_40 = new import11.ViewContainer(40,0,this,this._anchor_40);
    this._TemplateRef_40_5 = new import15.TemplateRef_(this,40,this._anchor_40);
    this._NgIf_40_6 = new import14.Wrapper_NgIf(this._vc_40.vcRef,this._TemplateRef_40_5);
    this._text_41 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._anchor_42 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_42 = new import11.ViewContainer(42,0,this,this._anchor_42);
    this._TemplateRef_42_5 = new import15.TemplateRef_(this,42,this._anchor_42);
    this._NgIf_42_6 = new import14.Wrapper_NgIf(this._vc_42.vcRef,this._TemplateRef_42_5);
    this._text_43 = this.renderer.createText((null as any),'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_8));
    this.init(this._text_43,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._anchor_40,
      this._text_41,
      this._anchor_42,
      this._text_43
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.RouterLinkWithHref) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._RouterLinkWithHref_8_3.context; }
    if (((token === import15.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import16.NgIf) && (20 === requestNodeIndex))) { return this._NgIf_20_6.context; }
    if (((token === import15.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import19.NgFor) && (35 === requestNodeIndex))) { return this._NgFor_35_6.context; }
    if (((token === import15.TemplateRef) && (40 === requestNodeIndex))) { return this._TemplateRef_40_5; }
    if (((token === import16.NgIf) && (40 === requestNodeIndex))) { return this._NgIf_40_6.context; }
    if (((token === import15.TemplateRef) && (42 === requestNodeIndex))) { return this._TemplateRef_42_5; }
    if (((token === import16.NgIf) && (42 === requestNodeIndex))) { return this._NgIf_42_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_8_0_0:any = this._arr_57('/portfolio');
    this._RouterLinkWithHref_8_3.check_routerLink(currVal_8_0_0,throwOnChange,false);
    this._RouterLinkWithHref_8_3.ngDoCheck(this,this._el_8,throwOnChange);
    const currVal_20_0_0:any = this.parentView.context.isImgNotNull(this.parentView.context.item.imageIndex);
    this._NgIf_20_6.check_ngIf(currVal_20_0_0,throwOnChange,false);
    this._NgIf_20_6.ngDoCheck(this,this._anchor_20,throwOnChange);
    const currVal_35_0_0:any = this.parentView.context.item.tags;
    this._NgFor_35_6.check_ngForOf(currVal_35_0_0,throwOnChange,false);
    this._NgFor_35_6.ngDoCheck(this,this._anchor_35,throwOnChange);
    const currVal_40_0_0:any = this.parentView.context.showMoreImages();
    this._NgIf_40_6.check_ngIf(currVal_40_0_0,throwOnChange,false);
    this._NgIf_40_6.ngDoCheck(this,this._anchor_40,throwOnChange);
    const currVal_42_0_0:any = (this.parentView.context.item.images != (null as any));
    this._NgIf_42_6.check_ngIf(currVal_42_0_0,throwOnChange,false);
    this._NgIf_42_6.ngDoCheck(this,this._anchor_42,throwOnChange);
    this._vc_20.detectChangesInNestedViews(throwOnChange);
    this._vc_35.detectChangesInNestedViews(throwOnChange);
    this._vc_40.detectChangesInNestedViews(throwOnChange);
    this._vc_42.detectChangesInNestedViews(throwOnChange);
    this._RouterLinkWithHref_8_3.checkHost(this,this,this._el_8,throwOnChange);
    const currVal_58:any = import3.inlineInterpolate(1,' ',((this.parentView.context.item == null)? (null as any): this.parentView.context.item.title),'\n      ');
    if (import3.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setText(this._text_12,currVal_58);
      this._expr_58 = currVal_58;
    }
    const currVal_59:any = this.parentView.context.item.description;
    if (import3.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setElementProperty(this._el_28,'innerHTML',this.viewUtils.sanitizer.sanitize(import13.SecurityContext.HTML,currVal_59));
      this._expr_59 = currVal_59;
    }
  }
  destroyInternal():void {
    this._vc_20.destroyNestedViews();
    this._vc_35.destroyNestedViews();
    this._vc_40.destroyNestedViews();
    this._vc_42.destroyNestedViews();
    this._RouterLinkWithHref_8_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
    cb(this._text_1,ctx);
    cb(this._el_2,ctx);
    cb(this._text_15,ctx);
    cb(this._el_16,ctx);
    cb(this._text_39,ctx);
    cb(this._vc_40.nativeElement,ctx);
    this._vc_40.visitNestedViewRootNodes(cb,ctx);
    cb(this._text_41,ctx);
    cb(this._vc_42.nativeElement,ctx);
    this._vc_42.visitNestedViewRootNodes(cb,ctx);
    cb(this._text_43,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 20)) { return new View_PortfolioDetailComponent3(this.viewUtils,this,20,this._anchor_20,this._vc_20); }
    if ((nodeIndex == 35)) { return new View_PortfolioDetailComponent4(this.viewUtils,this,35,this._anchor_35,this._vc_35); }
    if ((nodeIndex == 40)) { return new View_PortfolioDetailComponent5(this.viewUtils,this,40,this._anchor_40,this._vc_40); }
    if ((nodeIndex == 42)) { return new View_PortfolioDetailComponent8(this.viewUtils,this,42,this._anchor_42,this._vc_42); }
    return (null as any);
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_8_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
var renderType_PortfolioDetailComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_PortfolioDetailComponent,{});
export class View_PortfolioDetailComponent0 extends import1.AppView<import0.PortfolioDetailComponent> {
  _anchor_0:any;
  /*private*/ _vc_0:import11.ViewContainer;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import14.Wrapper_NgIf;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import11.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import14.Wrapper_NgIf;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PortfolioDetailComponent0,renderType_PortfolioDetailComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_0 = new import11.ViewContainer(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import15.TemplateRef_(this,0,this._anchor_0);
    this._NgIf_0_6 = new import14.Wrapper_NgIf(this._vc_0.vcRef,this._TemplateRef_0_5);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_2 = new import11.ViewContainer(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import15.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import14.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._anchor_0,
      this._text_1,
      this._anchor_2
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import16.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    if (((token === import15.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import16.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.showLoader;
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,false);
    this._NgIf_0_6.ngDoCheck(this,this._anchor_0,throwOnChange);
    const currVal_2_0_0:boolean = !this.context.showLoader;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
    this._vc_2.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 0)) { return new View_PortfolioDetailComponent1(this.viewUtils,this,0,this._anchor_0,this._vc_0); }
    if ((nodeIndex == 2)) { return new View_PortfolioDetailComponent2(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}