/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../ClientApp/app/portfolio/portfolio.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/http/src/http_module';
import * as import4 from '@angular/router/src/router_module';
import * as import5 from '../../../../ClientApp/app/portfolio/portfolio-routing.module';
import * as import6 from '@angular/common/src/localization';
import * as import7 from '@angular/http/src/backends/browser_xhr';
import * as import8 from '@angular/http/src/base_response_options';
import * as import9 from '@angular/http/src/backends/xhr_backend';
import * as import10 from '@angular/http/src/base_request_options';
import * as import11 from '../../../../ClientApp/app/portfolio/shared/portfolio.service';
import * as import12 from '@angular/core/src/di/injector';
import * as import13 from './portfolio.component.ngfactory';
import * as import14 from './portfolio-detail/portfolio-detail.component.ngfactory';
import * as import15 from '@angular/core/src/i18n/tokens';
import * as import16 from '../../../../ClientApp/app/portfolio/portfolio.component';
import * as import17 from '../../../../ClientApp/app/portfolio/portfolio-detail/portfolio-detail.component';
import * as import18 from '@angular/http/src/interfaces';
import * as import19 from '@angular/http/src/http';
import * as import20 from '@angular/router/src/router_config_loader';
class PortfolioModuleInjector extends import0.NgModuleInjector<import1.PortfolioModule> {
  _CommonModule_0:import2.CommonModule;
  _HttpModule_1:import3.HttpModule;
  _RouterModule_2:import4.RouterModule;
  _PortfolioRoutingModule_3:import5.PortfolioRoutingModule;
  _PortfolioModule_4:import1.PortfolioModule;
  __NgLocalization_5:import6.NgLocaleLocalization;
  __BrowserXhr_6:import7.BrowserXhr;
  __ResponseOptions_7:import8.BaseResponseOptions;
  __XSRFStrategy_8:any;
  __XHRBackend_9:import9.XHRBackend;
  __RequestOptions_10:import10.BaseRequestOptions;
  __Http_11:any;
  __ROUTES_12:any[];
  __PortfolioService_13:import11.PortfolioService;
  constructor(parent:import12.Injector) {
    super(parent,[
      import13.PortfolioComponentNgFactory,
      import14.PortfolioDetailComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_5():import6.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import6.NgLocaleLocalization(this.parent.get(import15.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _BrowserXhr_6():import7.BrowserXhr {
    if ((this.__BrowserXhr_6 == null)) { (this.__BrowserXhr_6 = new import7.BrowserXhr()); }
    return this.__BrowserXhr_6;
  }
  get _ResponseOptions_7():import8.BaseResponseOptions {
    if ((this.__ResponseOptions_7 == null)) { (this.__ResponseOptions_7 = new import8.BaseResponseOptions()); }
    return this.__ResponseOptions_7;
  }
  get _XSRFStrategy_8():any {
    if ((this.__XSRFStrategy_8 == null)) { (this.__XSRFStrategy_8 = import3._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_8;
  }
  get _XHRBackend_9():import9.XHRBackend {
    if ((this.__XHRBackend_9 == null)) { (this.__XHRBackend_9 = new import9.XHRBackend(this._BrowserXhr_6,this._ResponseOptions_7,this._XSRFStrategy_8)); }
    return this.__XHRBackend_9;
  }
  get _RequestOptions_10():import10.BaseRequestOptions {
    if ((this.__RequestOptions_10 == null)) { (this.__RequestOptions_10 = new import10.BaseRequestOptions()); }
    return this.__RequestOptions_10;
  }
  get _Http_11():any {
    if ((this.__Http_11 == null)) { (this.__Http_11 = import3.httpFactory(this._XHRBackend_9,this._RequestOptions_10)); }
    return this.__Http_11;
  }
  get _ROUTES_12():any[] {
      if ((this.__ROUTES_12 == null)) { (this.__ROUTES_12 = [[
        {
          path: 'portfolio',
          component: import16.PortfolioComponent
        }
        ,
        {
          path: 'portfolio/:slug',
          component: import17.PortfolioDetailComponent
        }

      ]
    ]); }
    return this.__ROUTES_12;
  }
  get _PortfolioService_13():import11.PortfolioService {
    if ((this.__PortfolioService_13 == null)) { (this.__PortfolioService_13 = new import11.PortfolioService(this._Http_11)); }
    return this.__PortfolioService_13;
  }
  createInternal():import1.PortfolioModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._HttpModule_1 = new import3.HttpModule();
    this._RouterModule_2 = new import4.RouterModule(this.parent.get(import4.ROUTER_FORROOT_GUARD,(null as any)));
    this._PortfolioRoutingModule_3 = new import5.PortfolioRoutingModule();
    this._PortfolioModule_4 = new import1.PortfolioModule();
    return this._PortfolioModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.HttpModule)) { return this._HttpModule_1; }
    if ((token === import4.RouterModule)) { return this._RouterModule_2; }
    if ((token === import5.PortfolioRoutingModule)) { return this._PortfolioRoutingModule_3; }
    if ((token === import1.PortfolioModule)) { return this._PortfolioModule_4; }
    if ((token === import6.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import7.BrowserXhr)) { return this._BrowserXhr_6; }
    if ((token === import8.ResponseOptions)) { return this._ResponseOptions_7; }
    if ((token === import18.XSRFStrategy)) { return this._XSRFStrategy_8; }
    if ((token === import9.XHRBackend)) { return this._XHRBackend_9; }
    if ((token === import10.RequestOptions)) { return this._RequestOptions_10; }
    if ((token === import19.Http)) { return this._Http_11; }
    if ((token === import20.ROUTES)) { return this._ROUTES_12; }
    if ((token === import11.PortfolioService)) { return this._PortfolioService_13; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const PortfolioModuleNgFactory:import0.NgModuleFactory<import1.PortfolioModule> = new import0.NgModuleFactory(PortfolioModuleInjector,import1.PortfolioModule);