/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../ClientApp/app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../ClientApp/app/components/navmenu.component';
import * as import9 from './components/navmenu.component.ngfactory';
import * as import10 from '@angular/core/src/linker/view_container';
import * as import11 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import12 from '@angular/router/src/router_outlet_map';
import * as import13 from '@angular/core/src/linker/component_factory_resolver';
import * as import14 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.AppComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent();
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  compView_0:import1.AppView<import8.NavMenuComponent>;
  _NavMenuComponent_0_3:import9.Wrapper_NavMenuComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  /*private*/ _vc_8:import10.ViewContainer;
  _RouterOutlet_8_5:import11.Wrapper_RouterOutlet;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'nav-menu',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import9.View_NavMenuComponent0(this.viewUtils,this,0,this._el_0);
    this._NavMenuComponent_0_3 = new import9.Wrapper_NavMenuComponent();
    this.compView_0.create(this._NavMenuComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_8 = new import10.ViewContainer(8,6,this,this._el_8);
    this._RouterOutlet_8_5 = new import11.Wrapper_RouterOutlet(this.parentView.injectorGet(import12.RouterOutletMap,this.parentIndex),this._vc_8.vcRef,this.parentView.injectorGet(import13.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_9 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n  ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_2,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_2,'footer',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n      ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','col-lg-12 text-right'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n          ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'a',new import3.InlineArray8(8,'class','btn btn-default btn-sm btn-back','href','https://github.com/CodingDK/','target','_blank','title','GitHub profil'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-2x fa-github-square'),(null as any));
    this._text_26 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_23,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'GitHub profil',(null as any));
    this._text_29 = this.renderer.createText(this._el_23,'\n          ',(null as any));
    this._text_30 = this.renderer.createText(this._el_21,' \n          ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_21,'a',new import3.InlineArray8(8,'class','btn btn-default btn-sm btn-back','href','https://www.linkedin.com/in/lasse-dahl-slot/','target','_blank','title','LinkedIn profil'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-2x fa-linkedin-square'),(null as any));
    this._text_34 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_31,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Linked profil',(null as any));
    this._text_37 = this.renderer.createText(this._el_31,'\n          ',(null as any));
    this._text_38 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._text_39 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_19,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'Sidst opdateret d. 20 marts 2017',(null as any));
    this._text_42 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_19,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'Copyright © ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_43,'a',new import3.InlineArray4(4,'href','https://www.linkedin.com/in/lasse-dahl-slot/','target','_blank'),(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'Lasse D. Slot',(null as any));
    this._text_47 = this.renderer.createText(this._el_43,' - 2017',(null as any));
    this._text_48 = this.renderer.createText(this._el_19,'\n      ',(null as any));
    this._text_49 = this.renderer.createText(this._el_17,'\n    ',(null as any));
    this._text_50 = this.renderer.createText(this._el_15,'\n  ',(null as any));
    this._text_51 = this.renderer.createText(this._el_2,'\n',(null as any));
    this._text_52 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray2(2,'deactivate',(null as any)),this.eventHandler(this.handleEvent_8));
    this._RouterOutlet_8_5.subscribe(this,this.eventHandler(this.handleEvent_8),false,true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import8.NavMenuComponent) && (0 === requestNodeIndex))) { return this._NavMenuComponent_0_3.context; }
    if (((token === import14.RouterOutlet) && (8 === requestNodeIndex))) { return this._RouterOutlet_8_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NavMenuComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._RouterOutlet_8_5.ngDoCheck(this,this._el_8,throwOnChange);
    this._vc_8.detectChangesInNestedViews(throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_8.destroyNestedViews();
    this.compView_0.destroy();
    this._RouterOutlet_8_5.ngOnDestroy();
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'deactivate')) {
      const pd_sub_0:any = ((<any>this.context.onDeactivate()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}